"""Generate README.md with contents table."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from code_extract.models import FormattedBlock


def generate_readme(
    blocks: list[FormattedBlock],
    output_dir: Path,
    source_dir: Path,
) -> Path:
    """Generate a README.md summarizing extracted modules."""
    lines: list[str] = [
        "# Extracted Code Modules",
        "",
        f"Source: `{source_dir}`",
        f"Extracted: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"Total items: {len(blocks)}",
        "",
        "## Contents",
        "",
        "| Name | Type | Language | Source File | Valid |",
        "|------|------|----------|-------------|-------|",
    ]

    for block in blocks:
        item = block.item
        valid = "Yes" if block.is_valid else f"No ({block.validation_error})"
        lines.append(
            f"| {item.qualified_name} | {item.block_type.value} "
            f"| {item.language.value} | `{item.file_path.name}:{item.line_number}` "
            f"| {valid} |"
        )

    lines.extend([
        "",
        "## Warnings",
        "",
    ])

    has_warnings = False
    for block in blocks:
        if not block.is_valid:
            has_warnings = True
            lines.append(f"- **{block.item.name}**: {block.validation_error}")

    if not has_warnings:
        lines.append("No warnings.")

    lines.extend(["", "---", f"Generated by code-extract v0.1.0", ""])

    readme_path = output_dir / "README.md"
    readme_path.write_text("\n".join(lines), encoding="utf-8")
    return readme_path
